blank_issues_enabled: false
contact_links:
    - name: Questions and Help
      url: https://github.com/NotesHubApp/git-essentials/discussions
      about: This issue tracker is not for support questions. Please refer to the GitHub Discussions for such help.
