blank_issues_enabled: true
contact_links:
    - name: Ask a Question
      url: https://github.com/NotesHubApp/git-essentials/discussions
      about: Ask questions and discuss with other community members
