/**
 * The {@link clone}, {@link fetch}, {@link push}, and {@link pull} commands all accept an the callback.
 *
 * Message events are for messages generated by the remote server and sent during `fetch` and `push` requests.
 * They are particularly useful if the remote server has custom git-hooks that print to the console.
 *
 * @example
 * You are writing a console application, and you want to simply print any server messages to standard out.
 *
 * ```typescript
 * import { clone } from 'git-essentials'
 * clone({
 *   ...,
 *   onMessage: console.log
 * })
 * ```
 *
 * @group Callbacks
 */
 export type MessageCallback = (message: string) => void | Promise<void>
