export * as Models from './models/index'
export * as Errors from './errors/index'

export { add } from './api/add'
export { addRemote } from './api/addRemote'
export { checkout } from './api/checkout'
// export { clone } from './api/clone'
export { commit } from './api/commit'
export { currentBranch } from './api/currentBranch'
export { fetch } from './api/fetch'
export { getConfig } from './api/getConfig'
export { getConfigAll } from './api/getConfigAll'
export { init } from './api/init'
export { log } from './api/log'
// export { merge } from './api/log'
// export { pull } from './api/pull'
// export { push } from './api/push'
export { remove } from './api/remove'
export { setConfig } from './api/setConfig'
