name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test (Node.js)
        run: npm run test -- --coverage

      - name: Test (Browsers)
        run: npm run test:browsers

      - name: Publish test results
        uses: dorny/test-reporter@v1
        with:
          name: Tests (Node.js)       # Name of the check run which will be created
          path: reports/report.xml    # Path to test results
          reporter: jest-junit        # Format of test results

      - name: 'Upload coverage reports'
        uses: codecov/codecov-action@v3

      - name: Generate documentation
        run: npm run gen-doc
